Add indicator dm020
opensafely/qof-diabetes pull request #9
Opened 2023-01-06 08:35 UTC by milanwiedemann

This PR is currently only to demonstrate the new changes to @cewalters.

I'm planning to follow these steps, but might deviate slightly if I realise that there's a better way:

1. add new variables to `variables_lib_dm.py` file (this will help us understand if there are any difficulties expressing QOF variables in ehrQL)
2. create dummy data test patients that will help us test if the QOF rules we are implementing (see next step) are selecting/rejecting the correct patients
3. translate QOF rules for dm020. we will need to create a new file for this dataset definition (e.g., `dataset_definition_dm020.py`). we will make use of the variables created in step 1.
4. run study on dummy data and check that the results are what we expect (manually or pytest)

2023-01-13 12:37 UTC, inglesp requested changes
There's a lot to like here (not least the incredibly helpful PR description), and I can see the benefits of having a separate library for the rules, which you then use in the different dataset definitions.

However, the approach you've taken doesn't look quite right -- but it shouldn't be too hard to fix, and none of your work to convert QOF rules into ehrQL is wasted.

The issue is that unclear from the code about where the `dataset` variable comes from and what it represents.  The data flow seems to be:

* in variable_lib_dm.py, create a `Dataset` instance and call this `dataset` in the module namespace
* in dataset_definition_dm020.py, import this thing called `dataset`
* in dataset_definition_dm020.py, pass `dataset` to `variable_lib_dm.add_diabetes_mellitus_register_variables`, and call whatever this function returns `dataset` (although it's actually the same object that `dataset` originally referrred to, so this is unnecessary)
* in dataset_definition_dm020.py, call various functions (eg `variable_lib_dm.get_dm_reg_r1`) without passing `dataset` to these functions, and instead using the thing called `dataset` in the namespace of the `variable_lib_dm` module, which happens to be the same object as the thing called `dataset` in the `dataset_definition_dm020` module

It doesn't actually seem to be a problem for this code, since it apparently works and gives you the answers you expect, but I think it would be a source of confusion (it certainly took me a few minutes of reading to make sure I'd understood exactly what was going on) which risks letting errors creep in if we use this pattern more widely.

One solution would be to instantiate the `Dataset` class in dataset_definition_dm020.py, and always pass a `dataset` parameter to each of your variable_lib_dm.py functions:

```
# dataset_definition_dm020.py

dataset = Dataset()
add_diabetes_mellitus_register_variables(dataset, index_date)  # note we don't change what `dataset` refers to here
dataset.dm_reg_r1 = get_dm_reg_r1(dataset)
```

and

```
# variable_lib_dm.py

add_diabetes_mellitus_register_variables(dataset, index_date):
    ...
    # don't return anything

def get_dm_reg_r1(dataset):
    return (dataset.dmres_dat < dataset.dmlat_dat) | (
        dataset.dmlat_dat.is_not_null() & dataset.dmres_dat.is_null()
    )
```

However, a more idiomatic approach might be to subclass `Dataset` with some helper methods in variable_lib_dm.py, and then instantiate that subclass in the indicator modules, and call the methods to set the variables on the dataset instance:

```
# dm_dataset.py (I prefer this to variable_lib_dm.py)

from databuilder import Dataset

class DmDataset(Dataset):
    def add_register_variables(self, index_date):
        prior_events = get_prior_events(index_date)
        self.reg_dat = practice_registration_as_of(index_date).start_date
        ...

    def add_dm_reg_r1(self):
        self.dm_reg_r1 = (self.dmres_dat < self.dmlat_dat) | (
            self.dmlat_dat.is_not_null() & self.dmres_dat.is_null()
        )
```

and

```
# dataset_definition_dm017.py

from dm_dataset import DmDataset

dataset = DmDataset()
dataset.add_register_variables(index_date)
dataset.add_dm_reg_r1()
...
```

What do you think?  I don't know whether you've encountered Python's class/object system before.  If this is new to you, I can talk you through it next week.

2023-01-23 09:24 UTC, milanwiedemann commented
I've addressed two points since your initial review:

1. The approach to use one subclass `class DmDataset(Dataset):`  for both the variables and business rules seems to be the the best one for now (instead of one subclass for the business rules and one for the variables).
    - First, all QOF variables can be added using:

    ```
    dataset = DmDataset()
    dataset.add_diabetes_mellitus_variables(index_date)
    ```

    - Next, business rules can be added to each dataset definition and combined as neede:

    ```
    # DM_REG rule 1:
    dataset.dm_reg_r1 = dataset.get_dm_reg_r1()

    # DM_REG rule 2:
    dataset.dm_reg_r2 = dataset.get_dm_reg_r2()

    dm_reg_select_r2 = dataset.dm_reg_r1 & ~dataset.dm_reg_r2
    ```

2. I decided to name all business rules based on the first time they appear in the business rules document. This is not ideal but seem to be the easiest solution (for now). At this point other options, e.g., (i) writing code for each business rule, or (ii) writing a function that allow the user to generate business rules logic would either result in code duplication or requite a complicate framework that may take considerable time to develop. While I think we should certainly keep the idea of a QOF rule generator in mind, I think we shouldn't optimise something we don't fully understand yet (we dont know all the edge cases of all QOF rules yet).

2023-01-23 11:10 UTC, milanwiedemann commented
just spoke to @iaindillingham, I'll add more information (e.g., index_date, cutoff_values) into the DmDataset subclass using something like

```
    def __init__(self, index_date, cut_off_1):
        self.index_date = index_date
        self.cut_off_1 = cut_off_1
        super().__init__()
```

2023-01-26 09:11 UTC, milanwiedemann commented
@inglesp following discussion with Dave on slack I'm now using a factory function instead of subclassing Dataset from databuilder. any more suggestions from you or can I merge now?

2023-01-26 15:01 UTC, inglesp approved these changes
Looks good, well done.  I've made a couple of small suggestions, but from a code perspective, I think you should merge it and move on.

I've not checked the implementation of all the rules very carefully.  How do you think we should do this?

2023-01-26 15:01 UTC, inglesp commented on analysis/dm_dataset.py
> +    bpdia_cutoff_val: float = None,
Apart from `index_date`, the function parameters are unused.  Can we drop them?

2023-01-26 15:01 UTC, inglesp commented on analysis/dm_dataset.py
> +    dataset.fraillat_dat = last_matching_event(prior_events, mildmodsev_frail_cod).date
Possibly just personal preference, so please ignore if you disagree...  I find this long block of continuous code hard to read, and would prefer it if there was an empty line before each `# Field number:` line.

2023-01-27 10:46 UTC, milanwiedemann commented on analysis/dm_dataset.py
> +    bpdia_cutoff_val: float = None,
yes, good point, thx for spotting

2023-01-27 10:51 UTC, milanwiedemann commented on analysis/dm_dataset.py
> +    dataset.fraillat_dat = last_matching_event(prior_events, mildmodsev_frail_cod).date
true, I agree and have changed it

2023-01-27 11:01 UTC, milanwiedemann commented
> I've not checked the implementation of all the rules very carefully. How do you think we should do this?

I think there are 2 parts to this:
1. checking that the translation of the clinical rules into ehrQL is correct. we probably need another pair of eyes, but I also think that writing tests (see next step) will help to catch any translation errors I made
2. testing that the code does exactly what I want it does (provided step 1 is correct). in #12  I moved the creation of test dummy data patients into an R script so that I can add more comments and was thinking to add a pytest to test the output files for each indicator

2023-01-30 08:26 UTC, merged